[unique_file_id]
"—Ç–µ—Ä–ø–∏" = "AgADcG4AAiWZuUk"
"—Ç–µ—Ä–ø–ª—é" = "AgADw3sAAo8vuUk"
"–Ω–∞–∫–∏–¥—ã–≤–∞–π" = "AgADumAAAk4okUk"

[categories]
good = ["—Ö–æ—Ä–æ—à–∏–π", "–æ—Ç–ª–∏—á–Ω—ã–π", "–ª—É—á—à–∏–π"]

[captcha_properties]
"length" = 5
"timer" = 60
"update_freq" = 10
"attempts" = 3
"bar_length" = 20

[sticker_to_sticker]
"—Ç–µ—Ä–ø–∏" = ["—Ç–µ—Ä–ø–ª—é"]
"—Ç–µ—Ä–ø–ª—é" = "—Ç–µ—Ä–ø–∏"
"–Ω–∞–∫–∏–¥—ã–≤–∞–π" = "–Ω–∞–∫–∏–¥—ã–≤–∞–π"

[text_to_text]
"—Å–æ–µ—Ä {good} –∏–Ω–∂–µ–Ω–µ—Ä" = ["–∏ —á–µ–ª–æ–≤–µ–∫ —Ö–æ—Ä–æ—à–∏–π"]
"–¥–µ–∫–∞–±—Ä–∏—Å—Ç {good} –∏–Ω–∂–µ–Ω–µ—Ä" = "–Ω–µ—Ç, —Å–æ–µ—Ä"
"–≤–ª–∞–¥ –º–∏—à—É—Å—Ç–∏–Ω" = "–ª—É—á—à–∏–π –±—É—Ç–∫–µ–º–ø –∑–∞ 500–∫"

"—Ç–∞–Ω–µ–Ω–±–∞—É–º–∞ –¥–∞–≤–∞–π —Ö—É–ª–∏" = [
    "–ß—Ç–æ —Ö–æ—Ä–æ—à–æ –≤ —Å—Ç–∞–Ω–¥–∞—Ä—Ç–∞—Ö, —Ç–∞–∫ —ç—Ç–æ —Ç–æ, —á—Ç–æ —É –≤–∞—Å –≤—Å–µ–≥–¥–∞ –µ—Å—Ç—å –∏–∑ —á–µ–≥–æ –≤—ã–±—Ä–∞—Ç—å. \n\n - –ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ —Å–µ—Ç–∏",
    "–í–µ—Ä–æ—è—Ç–Ω–æ, —Ç–∞–∫–∞—è —Å–∏—Ç—É–∞—Ü–∏—è —Å–ª–æ–∂–∏–ª–∞—Å—å –∏–∑-–∑–∞ –æ—à–∏–±–∫–∏ –æ–¥–Ω–æ–≥–æ –∏–∑ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Å—Ç–æ–≤ BIOS, –∫–æ—Ç–æ—Ä—ã–π –ø–∏—Å–∞–π —Å–≤–æ–π —à–µ–¥–µ–≤—Ä –Ω–∞ –∞—Å—Å–µ–º–±–ª–µ—Ä–µ 8088.\n\n - –ê—Ä—Ö–∏—Ç–µ–∫—Ç—É—Ä–∞ –∫–æ–º–ø—å—é—Ç–µ—Ä–∞",
    "–í –∫–æ–º–ø—å—é—Ç–µ—Ä–Ω–æ–π –æ—Ç—Ä–∞—Å–ª–∏ —Ç—Ä—É–¥–Ω–æ –ø–æ–¥–æ–±—Ä–∞—Ç—å –Ω–∞–∑–≤–∞–Ω–∏–µ, –∫–æ—Ç–æ—Ä–æ–µ –±—ã –Ω–µ –≤—ã–≥–ª—è–¥–µ–ª–æ —Å–º–µ—à–Ω–æ 30 –ª–µ—Ç —Å–ø—É—Å—Ç—è.\n\n - –ê—Ä—Ö–∏—Ç–µ–∫—Ç—É—Ä–∞ –∫–æ–º–ø—å—é—Ç–µ—Ä–∞",
    "–î–µ–º–æ–Ω - —Å–ª—É–∂–µ–±–Ω–∞—è –ø—Ä–æ–≥—Ä–∞–º–º–∞ –≤ –Ω–µ–∫–æ—Ç–æ—Ä—ã—Ö –æ–ø–µ—Ä–∞—Ü–∏–æ–Ω–Ω—ã—Ö —Å–∏—Å—Ç–µ–º–∞—Ö (–ø—Ä–µ–∏–º—É—â–µ—Å—Ç–≤–µ–Ω–Ω–æ –æ—Å–Ω–æ–≤–∞–Ω–Ω—ã—Ö –Ω–∞ UNIX), —Ä–∞–±–æ—Ç–∞—é—â–∞—è –≤ —Ñ–æ–Ω–æ–≤–æ–º —Ä–µ–∂–∏–º–µ –±–µ–∑ –Ω–µ–ø–æ—Å—Ä–µ–¥—Å—Ç–≤–µ–Ω–Ω–æ–≥–æ –≤–∑–∞–∏–º–æ–¥–µ–π—Å—Ç–≤–∏—è —Å –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–º.\n\n - –°–æ–≤—Ä–µ–º–µ–Ω–Ω—ã–µ –æ–ø–µ—Ä–∞—Ü–∏–æ–Ω–Ω—ã–µ —Å–∏—Å—Ç–µ–º—ã",
    "–ì–æ–ª–æ–¥–∞–Ω–∏–µ (–∑–∞–≤–∏—Å–∞–Ω–∏–µ –ø—Ä–æ—Ü–µ—Å—Å–∞) - —Å–∏—Ç—É–∞—Ü–∏—è, –∫–æ–≥–¥–∞ –≤—Å–µ –ø—Ä–æ–≥—Ä–∞–º–º—ã –±–µ—Å–∫–æ–Ω–µ—á–Ω–æ —Ä–∞–±–æ—Ç–∞—é—Ç, –Ω–æ –Ω–µ –º–æ–≥—É—Ç –¥–æ–±–∏—Ç—å—Å—è –Ω–∏–∫–∞–∫–æ–≥–æ –ø—Ä–æ–≥—Ä–µ—Å—Å–∞.\n\n - –°–æ–≤—Ä–µ–º–µ–Ω–Ω—ã–µ –æ–ø–µ—Ä–∞—Ü–∏–æ–Ω–Ω—ã–µ —Å–∏—Å—Ç–µ–º—ã",
    "–°–∞–º—ã–µ –±—ã—Å—Ç—Ä—ã–µ –±–ª–æ–∫–∏—Ä–æ–≤–∫–∏ - –æ—Ç—Å—É—Ç—Å—Ç–≤–∏–µ –≤—Å—è–∫–∏—Ö –±–ª–æ–∫–∏—Ä–æ–≤–æ–∫.\n\n - –°–æ–≤—Ä–µ–º–µ–Ω–Ω—ã–µ –æ–ø–µ—Ä–∞—Ü–∏–æ–Ω–Ω—ã–µ —Å–∏—Å—Ç–µ–º—ã",
    "–†–µ—Ü–µ–ø—Ç - —ç—Ç–æ –ø—Ä–æ–≥—Ä–∞–º–º–∞ (–∞–ª–≥–æ—Ä–∏—Ç–º, –≤—ã—Ä–∞–∂–µ–Ω–Ω—ã–π –≤ –Ω–µ–∫–æ–π —É–¥–æ–±–Ω–æ–π —Ñ–æ—Ä–º–µ –∑–∞–ø–∏—Å–∏), –ø—Ä–æ–≥—Ä–∞–º–º–∏—Å—Ç - —Ü–µ–Ω—Ç—Ä–∞–ª—å–Ω—ã–π –ø—Ä–æ—Ü–µ—Å—Å–æ—Ä, –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç—ã - –≤—Ö–æ–¥–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ, –ø—Ä–æ—Ü–µ—Å—Å - –¥–µ–π—Å—Ç–≤–∏—è, —Å–æ—Å—Ç–æ—è—â–∏–µ –∏–∑ —á—Ç–µ–Ω–∏—è —Ä–µ—Ü–µ–ø—Ç–∞, –≤—ã–ø–µ—á–∫–∏...\n\n - –°–æ–≤—Ä–µ–º–µ–Ω–Ω—ã–µ –æ–ø–µ—Ä–∞—Ü–∏–æ–Ω–Ω—ã–µ —Å–∏—Å—Ç–µ–º—ã",
    "–ê–≤—Ç–æ—Ä—ã —ç—Ç–æ–π –∫–Ω–∏–≥–∏ –ø—Ä–µ–¥—Å–∫–∞–∑—ã–≤–∞—é—Ç, —á—Ç–æ –∫–æ–Ω–µ—Ü —Ü–∏–≤–∏–ª–∏–∑–∞—Ü–∏–∏ –ø—Ä–æ–∏–∑–æ–π–¥–µ—Ç –≤ –ø–æ–ª–Ω–æ—á—å 31 –¥–µ–∫–∞–±—Ä—è 9999 –≥–æ–¥–∞, –∫–æ–≥–¥–∞ —Å—Ä–∞–∑—É —É–Ω–∏—á—Ç–æ–∂–∞—Ç—Å—è –≤—Å–µ –ø—Ä–æ–≥—Ä–∞–º–º—ã, –Ω–∞–ø–∏—Å–∞–Ω–Ω—ã–µ –∑–∞ 8000 –ª–µ—Ç –Ω–∞ —è–∑—ã–∫–µ COBOL.\n\n - –ê—Ä—Ö–∏—Ç–µ–∫—Ç—É—Ä–∞ –∫–æ–º–ø—å—é—Ç–µ—Ä–∞",
    "–í –∫–æ–º–ø—å—é—Ç–µ—Ä–Ω–æ–π –æ—Ç—Ä–∞—Å–ª–∏ —Ç—Ä—É–¥–Ω–æ –ø–æ–¥–æ–±—Ä–∞—Ç—å –Ω–∞–∑–≤–∞–Ω–∏–µ, –∫–æ—Ç–æ—Ä–æ–µ –±—ã –Ω–µ –≤—ã–≥–ª—è–¥–µ–ª–æ —Å–º–µ—à–Ω–æ 30 –ª–µ—Ç —Å–ø—É—Å—Ç—è.\n\n - –ê—Ä—Ö–∏—Ç–µ–∫—Ç—É—Ä–∞ –∫–æ–º–ø—å—é—Ç–µ—Ä–∞",
    "–ò—Å—Ç–æ—Ä–∏—á–µ—Å–∫–∏ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–ª–∏ –∏ —Ä–∞–∑–≤–∏–≤–∞–ª–∏ –∏—Å–∫—É—Å—Å—Ç–≤–æ –∫—Ä–∏–ø—Ç–æ–≥—Ä–∞—Ñ–∏–∏ –ø—Ä–µ–¥—Å—Ç–∞–≤–∏—Ç–µ–ª–∏ —á–µ—Ç—ã—Ä–µ—Ö –ø—Ä–æ—Ñ–µ—Å—Å–∏–π: –≤–æ–µ–Ω–Ω—ã–µ, –¥–∏–ø–ª–æ–º–∞—Ç–∏—á–µ—Å–∫–∏–π –∫–æ—Ä–ø—É—Å, –ª—é–¥–∏, –≤–µ–¥—É—â–∏–µ –¥–Ω–µ–≤–Ω–∏–∫, –∏ –ª—é–±–æ–≤–Ω–∏–∫–∏.",
    "–ë–æ–± –Ω–µ –∑–Ω–∞–µ—Ç –∑–∞–∫—Ä—ã—Ç–æ–≥–æ –∫–ª—é—á–∞ –ê–ª–∏—Å—ã, —Å–ª–µ–¥–æ–≤–∞—Ç–µ–ª—å–Ω–æ, –ø–æ–ª—É—á–∏—Ç—å –∑–∞—à–∏—Ñ—Ä–æ–≤–∞–Ω–Ω–æ–µ —ç—Ç–∏–º –∫–ª—é—á–æ–º —Å–æ–æ–±—â–µ–Ω–∏–µ –æ–Ω –º–æ–≥ —Ç–æ–ª—å–∫–æ –æ—Ç –ê–ª–∏—Å—ã. –°–∏–¥—è –≤ —Ç—é—Ä—å–º–µ –∑–∞ –ª–∂–µ—Å–≤–∏–¥–µ—Ç–µ–ª—å—Å—Ç–≤–æ –∏ –º–æ—à–µ–Ω–Ω–∏—á–µ—Å—Ç–≤–æ, –ê–ª–∏—Å–∞ —Å–º–æ–∂–µ—Ç –∑–∞–Ω—è—Ç—å—Å—è —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–æ–π –Ω–æ–≤—ã—Ö –∏–Ω—Ç–µ—Ä–µ—Å–Ω—ã—Ö –∞–ª–≥–æ—Ä–∏—Ç–º–æ–≤ —Å –æ—Ç–∫—Ä—ã—Ç—ã–º –∫–ª—é—á–æ–º.",
    "–ê—É–¥–∏–æ-–∫–æ–º–ø–∞–∫—Ç-–¥–∏—Å–∫–∏ —Å–æ–¥–µ—Ä–∂–∞—Ç –∑–≤—É–∫–æ–≤–æ–π —Å–∏–≥–Ω–∞–ª, –æ—Ü–∏—Ñ—Ä–æ–≤–∞–Ω–Ω—ã–π —Å —á–∞—Å—Ç–æ—Ç–æ–π –¥–∏—Å–∫—Ä–µ—Ç–∏–∑–∞—Ü–∏–∏ 44 100 –ì—Ü, –≤ —Ä–µ–∑—É–ª—å—Ç–∞—Ç–µ —á–µ–≥–æ –æ–Ω–∏ –º–æ–≥—É—Ç —Ö—Ä–∞–Ω–∏—Ç—å –∑–≤—É–∫–∏ —Å —á–∞—Å—Ç–æ—Ç–∞–º–∏ –¥–æ 22 –∫–ì—Ü, —á—Ç–æ –≤–æ—Å–ø—Ä–∏–Ω–∏–º–∞–µ—Ç—Å—è –∫–∞–∫ –¥–æ—Å—Ç–∞—Ç–æ—á–Ω–æ –∫–∞—á–µ—Å—Ç–≤–µ–Ω–Ω—ã–π –∑–≤—É–∫ –ª—é–¥—å–º–∏, –Ω–æ —Å—á–∏—Ç–∞–µ—Ç—Å—è –≤–µ—Å—å–º–∞ –Ω–∏–∑–∫–∏–º –∫–∞—á–µ—Å—Ç–≤–æ–º —Å—Ä–µ–¥–∏ —Å–æ–±–∞–∫, —Ü–µ–Ω—è—â–∏—Ö —Ö–æ—Ä–æ—à—É—é –º—É–∑—ã–∫—É.\n\n - –ö–æ–º–ø—å—é—Ç–µ—Ä–Ω—ã–µ —Å–µ—Ç–∏",
    "–ü—Ä–æ–µ–∫—Ç –±—ã–ª –Ω–∞–∑–≤–∞–Ω Bluetooth (¬´–°–∏–Ω–∏–π –∑—É–±¬ª) –≤ —á–µ—Å—Ç—å –≤–µ–ª–∏–∫–æ–≥–æ –∫–æ—Ä–æ–ª—è –≤–∏–∫–∏–Ω–≥–æ–≤ –ø–æ –∏–º–µ–Ω–∏ –ì–∞—Ä–∞–ª—å–¥ –°–∏–Ω–∏–π –ó—É–± II (940‚Äî981), –∫–æ—Ç–æ—Ä—ã–π –æ–±—ä–µ–¥–∏–Ω–∏–ª (—á–∏—Ç–∞–π, –∑–∞–≤–æ–µ–≤–∞–ª) –î–∞–Ω–∏—é –∏ –ù–æ—Ä–≤–µ–≥–∏—é. –ù—É –¥–∞, –æ–Ω —Ç–æ–∂–µ —Å–¥–µ–ª–∞–ª —ç—Ç–æ –±–µ–∑ –ø–æ–º–æ—â–∏ –ø—Ä–æ–≤–æ–¥–æ–≤.",
    "–í Unix-—Å–∏—Å—Ç–µ–º–∞—Ö –µ—Å—Ç—å –∫–æ–º–∞–Ω–¥–∞ - nice, –ø–æ–∑–≤–æ–ª—è—é—â–∞—è –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é –¥–æ–±—Ä–æ–≤–æ–ª—å–Ω–æ —Å–Ω–∏–∑–∏—Ç—å –ø—Ä–∏–æ—Ä–∏—Ç–µ—Ç —Å–≤–æ–µ –ø—Ä–æ—Ü–µ—Å—Å–∞, —á—Ç–æ–±—ã —É–≥–æ–¥–∏—Ç—å –¥—Ä—É–≥–∏–º –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è–º, –Ω–æ –µ—é –Ω–∏–∫—Ç–æ –Ω–∏–∫–æ–≥–¥–∞ –Ω–µ –ø–æ–ª—å–∑—É–µ—Ç—Å—è.",
]

"–ø–æ—Å–æ–≤–µ—Ç—É–π –∞–Ω–∏–º–µ" = [
    "https://myanimelist.net/anime/6213/Toaru_Kagaku_no_Railgun",
    "https://myanimelist.net/anime/8023/Toaru_Kagaku_no_Railgun__Motto_Marutto_Railgun",
    "https://myanimelist.net/anime/9047/Toaru_Kagaku_no_Railgun__Misaka-san_wa_Ima_Chuumoku_no_Mato_desu_kara",
    "https://myanimelist.net/anime/9063/Toaru_Kagaku_no_Railgun__Entenka_no_Satsuei_Model_mo_Raku_Ja_Arimasen_wa_ne",
    "https://myanimelist.net/anime/16049/Toaru_Kagaku_no_Railgun_S",
    "https://myanimelist.net/anime/19697/Toaru_Kagaku_no_Railgun_S__Motto_Marutto_Railgun",
    "https://myanimelist.net/anime/22759/Toaru_Kagaku_no_Railgun_S__Daiji_na_Koto_wa_Zenbu_Sentou_ni_Osowatta",
    "https://myanimelist.net/anime/38481/Toaru_Kagaku_no_Railgun_T",
    "https://myanimelist.net/anime/61012/Toaru_Kagaku_no_Railgun_4th_Season",
]

[text_to_sticker]
"—Ç–µ—Ä–ø–∏" = ["—Ç–µ—Ä–ø–ª—é"]
"—Ç–µ—Ä–ø–ª—é" = "—Ç–µ—Ä–ø–∏"
"–Ω–∞–∫–∏–¥—ã–≤–∞–π –Ω–∞–∫–∏–¥—ã–≤–∞–π" = "–Ω–∞–∫–∏–¥—ã–≤–∞–π"

[long_message]
message_max_len = 80
long_message = [
    "–ú–Ω–æ–≥–∞ –±—É–∫–∞–≤, –Ω–µ –æ—Å–∏–ª–∏–ª–∞!",
    "–ú–æ–∂–Ω–æ –ø–æ–∫–æ—Ä–æ—á–µ? –ê —Ç–æ –ª–µ–Ω—å —á–∏—Ç–∞—Ç—å))0)",
    "–¢—ã —Ç—Ä–∞—Ç–∏—à—å –º–æ–µ –≤—Ä–µ–º—è! –ü–µ—Ä–µ—Å–∫–∞–∂–∏ –≤ –¥–≤—É—Ö —Å–ª–æ–≤–∞—Ö!",
]

[custom-titles]
adjectives = ["—Ç—É—à–µ–Ω—ã–π", "—É–±–æ–π–Ω—ã–π", "—É–≥—Ä—é–º—ã–π", "—Ö–ª–µ–±–Ω—ã–π", "–º–µ—Ä—Ç–≤—ã–π", "–ª–æ–≤–∫–∏–π"]
nouns = ["–≤–∞—Ä–µ–Ω–∏–∫", "–≤–æ—Ä–æ–±–µ–π", "–æ–ª–µ–Ω—å", "—Ç—é–ª–µ–Ω—å", "–≥–Ω–æ–º", "–≥—É—Å—å"]

[[drink-or-not]]
emoji = ["ü•Ç","üçæ","üçª","üç∫"]
answer = [
    "–ù—É –∞ –ø–æ—á–µ–º—É –±—ã –∏ –¥–∞?",
    "–°–∞–º–æ —Å–æ–±–æ–π!",
    "–û–¥–Ω–æ–∑–Ω–∞—á–Ω–æ, —Å–µ–≥–æ–¥–Ω—è —Ç–æ—Ç —Å–∞–º—ã–π –¥–µ–Ω—å!",
    "–î–∞–≤–∞–π, –Ω–∏–∫—Ç–æ –Ω–µ –æ—Å—É–¥–∏—Ç.",
    "–ñ–∏–∑–Ω—å —Å–ª–∏—à–∫–æ–º –∫–æ—Ä–æ—Ç–∫–∞ –¥–ª—è —Ä–∞–∑–¥—É–º–∏–π!",
]

[[drink-or-not]]
emoji = ["ü•õ","üßÉ","‚òï"]
answer = [
    "–ù–µ, —Å–µ–≥–æ–¥–Ω—è –Ω–µ —Ç–æ—Ç –¥–µ–Ω—å.",
    "–õ—É—á—à–µ –æ—Ç–ª–æ–∂–∏ –Ω–∞ –ø–æ—Ç–æ–º.",
    "–ó–∞–≤—Ç—Ä–∞ —Å–ø–∞—Å–∏–±–æ —Å–∫–∞–∂–µ—à—å, –µ—Å–ª–∏ –Ω–µ –±—É–¥–µ—à—å.",
    "–°–µ–≥–æ–¥–Ω—è –±–µ–∑ —ç—Ç–æ–≥–æ, –Ω—É –µ–≥–æ.",
    "–ü—É—Å—Ç—å –æ—Ä–≥–∞–Ω–∏–∑–º –æ—Ç–¥–æ—Ö–Ω—ë—Ç.",
]